changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot[bot]
  categories:
    - title: New capabilities
      labels: [enhancement, feature]
    - title: Fixes
      labels: [bug, fix]
    - title: Documentation
      labels: [documentation]
    - title: Maintenance
      labels: [dependencies, maintenance]
    - title: Other changes
      labels: ["*"]
